alerts:
  enabled: false
  metricsPort: 8080
  severity: warning
debug: null
global:
  cattle:
    clusterName: ''
  kubectl:
    repository: rancher/kubectl
    tag: v1.34.1
image:
  operator:
    repository: rancher/compliance-operator
    tag: v1.3.3
  securityScan:
    repository: rancher/security-scan
    tag: v0.8.3
  sonobuoy:
    repository: rancher/mirrored-sonobuoy-sonobuoy
    tag: v0.57.3

